CREATE DATABASE CUP2018;

USE CUP2018;

CREATE TABLE USERS (
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(255) NOT NULL,
	USEREMAIL VARCHAR(255) NOT NULL,
	USERNICKNAME VARCHAR(100) NOT NULL,
	USERPASSWORD VARCHAR(20) NOT NULL,
	USERLOCATION VARCHAR(255) NOT NULL,
	PRIMARY KEY (USERID));

CREATE USER 'cup2018user'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT ALL PRIVILEGES ON *.* TO 'cup2018user'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `cup2018`.* TO 'cup2018user'@'%';